In [3]:
import numpy as np

# Basic Indexing and Slicing 

If you assign a scalar value to a slice, as in arr[5:8] = 12, the value is propagated (or broadcasted henceforth) to the entire selection. An important first distinction from Python’s built-in lists is that array slices are views on the original array. This means that the data is not copied, and any modifications to the view will be reflected in the source array:

In [20]:
arr = np.arange(9)

In [21]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
arrSlice = arr[5:8]

In [23]:
arrSlice

array([5, 6, 7])

In [24]:
arr[5:8] = 12

In [25]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8])

In [26]:
arrSlice = arr[5:8]

In [27]:
arrSlice

array([12, 12, 12])

In [28]:
arrSlice[1] = 12345

In [29]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8])

In [30]:
arrSlice[:] = 64

In [31]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8])

If you want a copy of a slice instead of a view --> need to explicitly copy array

In [32]:
arr[5:8].copy()

array([64, 64, 64])